### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by Elimelech** [White-Light-Dev/Screen-time#1]
# python3 main.py
  File "main.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by White-Light-Dev** [comment]
Hello, what is your OS?

**Comment by White-Light-Dev** [comment]
If you have linux, manually give the execution rights to the script notification.sh

**Comment by Elimelech** [comment]
I have a freeBSD OS

**Comment by Elimelech** [comment]
# sh notification.sh
notification.sh: 7: Syntax error: newline unexpected (expecting word)

**Comment by Elimelech** [comment]
And where are these files in which folder to download everything?

**Comment by White-Light-Dev** [comment]
Do you have a zenity library?

**Comment by Elimelech** [comment]
# pkg info zenity
zenity-3.32.0
Name           : zenity
Version        : 3.32.0
Installed on   : Mon May 31 19:24:51 2021 EEST
Origin         : x11/zenity
Architecture   : FreeBSD:13:i386
Prefix         : /usr/local
Categories     : x11 gnome
Licenses       : LGPL20
Maintainer     : gnome@FreeBSD.org
WWW            : UNKNOWN
Comment        : Display GNOME dialogs from the command line
Options        :
	NOTIFY         : on
Shared Libs required:
	libX11.so.6
	libnotify.so.4
	libglib-2.0.so.0
	libgobject-2.0.so.0
	libpango-1.0.so.0
	libharfbuzz.so.0
	libcairo.so.2
	libgtk-3.so.0
	libintl.so.8
	libcairo-gobject.so.2
	libatk-1.0.so.0
	libgdk_pixbuf-2.0.so.0
	libgio-2.0.so.0
	libgdk-3.so.0
	libpangocairo-1.0.so.0
Annotations    :
	FreeBSD_version: 1300139
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 6.51MiB
Description    :
Zenity allows dialog boxes to be created and displayed from the
commandline.  This provides a simple way to create a GUI for
a shell script.

**Comment by White-Light-Dev** [comment]
Maybe you have problems with the config.py file?

**Comment by Elimelech** [comment]
The configuration file is the same:


How to build this program in general? There are three separate files (notification.sh, main.py, config.py) - what to do with them?

**Comment by White-Light-Dev** [comment]
python3 main.py

**Comment by Elimelech** [comment]
# python3 /home/luba/Downloads/main.py
  File "/home/luba/Downloads/main.py", line 7
    <!DOCTYPE html>
  
SyntaxError: invalid syntax

**Comment by Elimelech** [comment]
How to build this program in general?

**Comment by Elimelech** [comment]
Understood. I have not downloaded the files correctly from the github site. They turned out to be html content.

Downloaded correctly, but now a new problem:

# python3 /home/luba/Downloads/main.py
chmod: notification.sh: No such file or directory

**Comment by Elimelech** [comment]
Разобрался. Я не правильно скачал файлы с сайта github. Они получились содержанием html.

Скачал правильно, но теперь новая проблема:
# python3 /home/luba/Downloads/main.py
chmod: notification.sh: No such file or directory

Программа зависает и дальше ничего не происходит!

**Comment by White-Light-Dev** [comment]
Check the files they should be in the same directory

**Comment by Elimelech** [comment]
Программа в той же директории. Удалил в файл строчку  os.system("chmod +x notification.sh") # выдаём право на исполнение

Установил руками права на файл.

**Comment by White-Light-Dev** [comment]
It's working?

**Comment by White-Light-Dev** [comment]
Это работает?

**Comment by Elimelech** [comment]
да, всё работает. Спасибо! Полезная программа. А какие дальнейшие доработки планируете?

**Comment by White-Light-Dev** [comment]
Пока что никаких, я ещё не придумал

**Comment by Elimelech** [comment]
А можно что-то такое доработать? А как остановить срипт? Нет такой кнопки. Когда появляется уведомление, то там только "отмена" или "ок". Но кнопка "отмена" не останавливает крипт. Допустим  вообще хочу откючить выполнение скрипта. такое можно сделать?

**Comment by White-Light-Dev** [comment]
Нет, но идея хорошая

**Comment by Elimelech** [comment]
А если я делаю вот так, то выдаёт ошибку:
root@A9t:/home/luba # /usr/local/bin/python3
Python 3.8.12 (default, Sep 11 2021, 01:15:26) 
[Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> main.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'main' is not defined
>>> /home/luba/Downloads/main.py
  File "<stdin>", line 1
    /home/luba/Downloads/main.py
    ^
SyntaxError: invalid syntax
>>> 

что я делаю не так?
В файле main.py эта строчка такая:  #!/usr/local/bin/python3

**Comment by White-Light-Dev** [comment]
Я не совсем понимаю что вы сделали, расскажите подробнее

**Comment by Elimelech** [comment]
Я запустил в терминале python3:
1) команда: #  /usr/local/bin/python3
>>>
2) запускаю сам срипт:
>>> home/luba/Downloads/main.py

И вывод:
File "<stdin>", line 1
    /home/luba/Downloads/main.py
    SyntaxError: invalid syntax

**Comment by Elimelech** [comment]
File <stdin>, line 1

**Comment by Elimelech** [comment]
File stdin, line 1

**Comment by White-Light-Dev** [comment]
Не знаю, не сталкивался с таким.

**Comment by White-Light-Dev** [comment]
Я прислушался к вашей идее. Теперь появилась кнопка отключения. Скоро будет на github.

**Comment by White-Light-Dev** [comment]
Здраствуйте, вышла новая версия 2.0

**Comment by Elimelech** [comment]
Отличная новость, сегодня попробую...

**Comment by Elimelech** [comment]
Что я не пойму с найтройками времени в файле config.py.
Вот смотри на срине: https://ibb.co/ChPqRsP
Выставил working_hours = 5 а в сообщении пишет 5 часов, но не прошло же 5 часов, что я работал за копьютером. Или я не понял как работает программа?

**Comment by White-Light-Dev** [comment]
Это у меня сообщение не правильно отображает, сейчас исправлю

**Comment by White-Light-Dev** [comment]
Спасибо, что помогаете мне в поисках багов и недостатков моих программ

**Comment by White-Light-Dev** [comment]
> Что я не пойму с найтройками времени в файле config.py.
> Вот смотри на срине: https://ibb.co/ChPqRsP
> Выставил working_hours = 5 а в сообщении пишет 5 часов, но не прошло же 5 часов, что я работал за копьютером. Или я не понял как работает программа?

Я уже исправил

**Comment by Elimelech** [comment]
Опробовал, работает. Спасибо!

**Comment by Elimelech** [comment]
А может добавить какую-то световую индикацию всплывающего окна?

**Comment by White-Light-Dev** [comment]
Можете пояснить более подробно?

**Comment by Elimelech** [comment]
Ну, например, чтобы заголовок всплывающего окна мигал(или что-то в этом роде), чтобы хоть как-то привлечь более внимание на экране. Можно конечно и звуковую сигнализацию прикрутить, но думаю не всем понравиться. Если бы как опцию, которую можно отключить, то да.

**Comment by White-Light-Dev** [comment]
Я не смог сделать мигание заголовка, но теперь есть звуковой сигнал(если у вас включен системный звук), который можно отключить
